console.log """
%c
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXOkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMd    dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMl    lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMl    lMMMMMMMMMMMMMMMk,;;::cclooxkkkOO00KXXNMMMMM
MMMMMO::;::::;;.    .,;;;::::coKMMMX;                .....'c0MMM
MMMMMl                        .xMMMNxc::;.                 .kMMM
MMMMMx........        ........:0MMMMMMMMX:    :00OOkkkc.   .kMMM
MMMMMWNXXXK000x.    .x000KXXXXWMMMMMMMMWo    .OMMMMMMMk.   .kMMM
MMMMMMMMMMMMMMK,    ,KMMMMMMMMMMMMMMMMMO.    oWMMMMMMMk.   .kMMM
MMMMMMMMMMMMMMN:    cWMMMMMMMMMMMMMMMMN:    ,KMMMMMMMMx.   .OMMM
MMN0OOOOOOOOOOO;    ;OOOOOOO00000KNMMWd.   .xMMMMMMMMMd    ,0MMM
MMx.                         .....xMM0'    :XMMMMMMMMMd    ,KMMM
MMx.                              dMWl    '0MMMMMN0OOk:    ;XMMM
MMN0kkkxooooool'    .coooooodkkkkOXMXc.  .xMMMMMMO'        lMMMM
MMMMMMMMMMMMMMMl    ,0MMMMMMMMMMMMMMMNKkokWMMMMMMNxc::;::::OMMMM
MMMMMMMMMMMMMMMl    .kXXXNMMMMMMMMMMMMMWNXXXXXXXXXXXXNMMMMMMMMMM
MMMMMMMMMMMMMMMl     ....',;;dXMMMM0c,;,.............',,;oKMMMMM
MMMMMM0xOKNMMMMo             :NMMMMx.                    .kMMMMM
MMMMM0,  .:KMMMd    .cxooooll0MMMMMd    .ckkkkkkkkkk,    .kMMMMM
MMMMWl    :NMMMx.   .kMMMMMMMMMMMMMd    .kMMMMMMMMMMl    .kMMMMM
MMMMk.   .OMMMMO,...,OMMMMMMMMMMMMMd    .kMMMMMMMMMMl    .kMMMMM
MMMN:    lWMMMMWX000XWMMMMMMMMMMMMMd.   .kMMMMMMMMMMl    .kMMMMM
MMMx.   .l0KNWMMMMMMMMMMMMMMMMMMMMMk.    ,cccccccccc.    .kMMMMM
MMX:       ..,;:loxkO0XWMMMMMMMMMMMk.                    .OMMMMM
MMKo;'.              ..';::lox0WMMMXOdoolccccccc::::cccccxNMMMMM
MMMMMNK0Odoc:;'..             lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWX0Okxdlc:;;'..'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""", "color: white; background: #ff0000"
